spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  route:
    front: http://localhost:8000

jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

llm:
  gemini:
    key: ''